Fix data not controlled by `var.enabled`
cloudposse/terraform-aws-kops-metadata pull request #10
Opened 2019-11-04 09:25 UTC by yujunz

Closes #9

2019-11-04 16:21 UTC, aknysh commented on outputs.tf
> +  value       = "${data.aws_iam_role.masters.*.id}"
```suggestion
  value       = "${join("", data.aws_iam_role.masters.*.id)}"
```

2019-11-04 16:22 UTC, aknysh commented on outputs.tf
> +  value       = "${data.aws_iam_role.masters.*.arn}"
```suggestion
  value       = "${join("", data.aws_iam_role.masters.*.arn)}"
```

2019-11-04 16:22 UTC, aknysh commented on outputs.tf
> +  value       = "${data.aws_iam_role.nodes.*.id}"
```suggestion
  value       = "${join("", data.aws_iam_role.nodes.*.id)}"
```

2019-11-04 16:22 UTC, aknysh commented on outputs.tf
> +  value       = "${data.aws_iam_role.nodes.*.arn}"
```suggestion
  value       = "${join("", data.aws_iam_role.nodes.*.arn)}"
```

2019-11-04 16:23 UTC, aknysh requested changes
thanks @yujunz , looks good, please see a few comments.
Also, please run `terraform fmt` to format the code, and run

```
make init
make readme/deps
make readme
```

to rebuild README

thanks

2019-11-05 03:35 UTC, yujunz commented
Done @aknysh 

There was an error when running `make readme`. I have to install gomplate manually to workaround it.

```
❯ make readme
curl --retry 3 --retry-delay 5 --fail -sSL -o /Users/yujunz/Code/github.com/cloudposse/terraform-aws-kops-metadata/build-harness/vendor/terraform-docs https://github.com/segmentio/terraform-docs/releases/download/v0.4.5/terraform-docs-v0.4.5-darwin-amd64 && chmod +x /Users/yujunz/Code/github.com/cloudposse/terraform-aws-kops-metadata/build-harness/vendor/terraform-docs
make: gomplate: No such file or directory
make: *** [readme/build] Error 1
```

2019-11-05 03:38 UTC, yujunz commented
Is it possible to have GitHub Actions to take the chore of formatting and updating, e.g. suggest changes automatically after running `terraform fmt` and `make ...`.

2019-11-06 18:09 UTC, aknysh approved these changes
thanks @yujunz

2019-11-06 18:09 UTC, merged